export const PERMISSIONS = {
  EMPLOYEE_READ: "employee.read",
  EMPLOYEE_WRITE: "employee.write",
  ATTENDANCE_READ: "attendance.read",
  ATTENDANCE_WRITE: "attendance.write",
  SHIFT_READ: "shift.read",
  SHIFT_WRITE: "shift.write",
  LEAVE_READ: "leave.read",
  LEAVE_WRITE: "leave.write",
  LEAVE_APPROVE: "leave.approve",
  RECRUITMENT_READ: "recruitment.read",
  RECRUITMENT_WRITE: "recruitment.write",
  AUDIT_READ: "audit.read",
  PAYROLL_READ: "payroll.read",
  PAYROLL_WRITE: "payroll.write",
  SETTINGS_READ: "settings.read",
  SETTINGS_WRITE: "settings.write",
  USER_READ: "user.read",
  USER_WRITE: "user.write"
} as const;

type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * Role → permissions. No unnecessary access.
 * EMPLOYEE: attendance, leave (read+write), payroll read, help only.
 * MANAGER: employee read, attendance, leave read+approve, recruitment read. No payroll/shifts/analytics/settings.
 * HRBP: employees, leave, recruitment, attendance, settings (policies). No payroll/shifts/analytics.
 * PAYROLL_MANAGER: employee read, attendance read, payroll, audit. No recruitment/leave/settings.
 */
const ROLE_PERMISSION_MAP: Record<string, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  HRMS_ADMIN: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.SHIFT_READ,
    PERMISSIONS.SHIFT_WRITE,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_WRITE,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.RECRUITMENT_READ,
    PERMISSIONS.RECRUITMENT_WRITE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_WRITE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_WRITE
  ],
  HRBP: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_WRITE,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.RECRUITMENT_READ,
    PERMISSIONS.RECRUITMENT_WRITE,
    PERMISSIONS.SETTINGS_READ
  ],
  PAYROLL_MANAGER: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_WRITE,
    PERMISSIONS.AUDIT_READ
  ],
  MANAGER: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.RECRUITMENT_READ
  ],
  EMPLOYEE: [
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_WRITE,
    PERMISSIONS.PAYROLL_READ
  ],
  HR_ADMIN: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.SHIFT_READ,
    PERMISSIONS.SHIFT_WRITE,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_WRITE,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.RECRUITMENT_READ,
    PERMISSIONS.RECRUITMENT_WRITE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_WRITE
  ]
};

export function hasPermission(role: string, permission: Permission): boolean {
  return (ROLE_PERMISSION_MAP[role] ?? []).includes(permission);
}
